### ISSUE TITLE
production ready

### ISSUE THREAD

**Issue by aterreno** [dorightdigital/js-config#1]
is this production ready? @matcarey

**Comment by nataliecarey** [comment]
Version 1.0 is released on NPM http://npmsearch.com/?q=js-config - it's covered by (what I believe to be) a robust suite of tests https://github.com/dorightdigital/js-config/blob/master/spec/usageExamplesSpec.js and (other than this one) doesn't have any bugs raised against it.

Is it perfect?  No.
Will it be perfect later? Maybe, maybe not.
Will it impress you beyond your wildest dreams? No.

Does it do what it says on the tin?  I believe so.

I'm using it in production on a project or two.  As always it's a personal/project decision whether or not to trust a library.  If you have a specific requirement before you're willing to use it in production feel free to raise a more specific issue and we can discuss it.

Mat

**Comment by aterreno** [comment]
Thanks for your prompt reply @matcarey, looking forward to use it in production then!
